version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    ports:
      - '80:3000'
    environment:
      DDATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/prisma_db"
      NEXT_PUBLIC_API_URL: ""
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: prisma_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg-data: