services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: prisma_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/prisma_db"
      NEXT_PUBLIC_API_URL: "http://prof.smartbolashaq.kz/"
    depends_on:
      - db

volumes:
  pg_data: