services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpassword@db:5432/prisma_db"
      NEXT_PUBLIC_API_URL: "https://localhost:3000"
    depends_on:
      - db
    command: sh -c "until nc -z db 5432; do echo Waiting for db; sleep 1; done && npm run start"

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: prisma_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: